name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Version
      run: ./script/check_version.sh ${{ inputs.version }}
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "v${{ inputs.version }}"
        tag_exists_error: false

